name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-test:
    name: Backend Test (Golang)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Run Go Tests (User Service)
        working-directory: ./backend/user-service
        run: go test -v ./...

      - name: Run Go Tests (Booking Service)
        working-directory: ./backend/booking-service
        run: go test -v ./...

      - name: Run Go Tests (Payment Service)
        working-directory: ./backend/payment-service
        run: go test -v ./...

  frontend-test:
    name: Frontend Test (React)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run tests
        working-directory: ./frontend
        run: npm run test -- --watchAll=false
